#!/bin/env bash

echo
echo "========Chrony sources==========="
sudo chronyc sources
echo
echo "========Chrony sources stats==========="
sudo chronyc sourcestats
echo
echo "========Chrony offsets==========="
./survDateOffset.py
echo
echo "========Ina 219 Astralim==========="
./ina219.py
echo
echo "========1 Wire==========="
./collect1wire.py
echo 
echo "========bme280==========="
#./bme280_lib.py
echo "========================="

